package ru.iopump.qa.allure.helper.plugin.youtrack;

import org.junit.jupiter.api.Test;
import ru.iopump.qa.allure.helper.plugin.youtrack.MarkdownStatisticModel.Footer;
import ru.iopump.qa.allure.helper.plugin.youtrack.MarkdownStatisticModel.Row;
import ru.iopump.qa.allure.helper.plugin.youtrack.MarkdownStatisticModel.Row.Statistic;
import ru.iopump.qa.allure.helper.plugin.youtrack.MarkdownStatisticModel.Total;

import java.util.List;

class MarkdownStatisticModelTest {

    String message = """

        ### E2E testing scenarios

        | **Scenario** | ❌ `Failed`                                 | ✅ `Passed`                                 |
        |--------------|--------------------------------------------|--------------------------------------------|
        | Scenario 1       | **2** times [`latest` on 01.01.2024](link) | **3** times [`latest` on 01.01.2024](link) |
        | Scenario 5       | **6** times [`latest` on 01.01.2023](link) | **7** times [`latest` on 01.01.2023](link) |

        Total test scenarios: **2**

        _Generated by [Allure Report Plugin - YouTrack Plugin](link)_

        """;

    @Test
    void toMarkdown() {
        var model = new MarkdownStatisticModel(
            "E2E testing scenarios",
            List.of(
                new Row(
                    "Data 1",
                    new Statistic(2, "latest", "01.01.2024"),
                    new Statistic(3, "latest", "01.01.2024")
                ),
                new Row(
                    "Data 5",
                    new Statistic(6, "latest", "01.01.2023"),
                    new Statistic(7, "latest", "01.01.2023")
                )
            ),
            new Total(2),
            new Footer(
                "Allure Report Plugin",
                "link"
            )
        );
        System.out.println(model.toMarkdown());
    }

    @Test
    void toModel() {
        var model = MarkdownStatisticModel.toModel(message);
        System.out.println(model.toMarkdown());
    }

    @Test
    void merge() {
        var modelV1 = MarkdownStatisticModel.toModel(message);
        var modelV2 = new MarkdownStatisticModel(
            "E2E testing scenarios",
            List.of(
                new Row(
                    "Scenario 0",
                    new Statistic(2, "latest", "10.10.2025"),
                    new Statistic(3, "latest", "10.10.2025")
                ),
                new Row(
                    "Scenario 1",
                    new Statistic(2, "latest", "10.10.2025"),
                    new Statistic(3, "latest", "10.10.2025")
                ),
                new Row(
                    "Scenario 5",
                    Statistic.error,
                    Statistic.error
                ),
                new Row(
                    "Scenario 10",
                    new Statistic(0, "latest", "00.00.2026"),
                    new Statistic(0, "latest", "00.00.2026")
                )
            ),
            new Total(4),
            new Footer(
                "Allure Report Plugin",
                "link"
            )
        );

        var merged = modelV1.merge(modelV2);

        System.out.println(merged.toMarkdown());
    }
}
