{{- if .Values.ingress.enabled }}
  {{- $servicePort := .Values.service.port -}}
  {{- $serviceName := "allure-server-service" -}}
  {{- $ingressExtraPaths := .Values.ingress.extraPaths -}}
---
  { {- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
  {{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
  {{- else -}}
apiVersion: extensions/v1beta1
  {{- end }}

kind: Ingress
metadata:
  name: allure-server-ingress
  annotations:
  {{ toYaml .Values.ingress.annotations | nindent 4 }}
  labels:
  {{- if .Values.ingress.labels }}
  {{ toYaml .Values.ingress.labels | indent 4 }}
  {{- end }}
  {{- include "allure-server.labels" . | nindent 4 }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .name }}
      http:
        paths:
          {{- range $ingressExtraPaths }}
          - path: {{ default "/" .path | quote }}
            backend:
              serviceName: {{ default $serviceName .service }}
              servicePort: {{ default $servicePort .port }}
          {{- end }}
          - path: {{ default "/" .path | quote }}
            backend:
              serviceName: {{ default $serviceName .service }}
              servicePort: {{ default $servicePort .servicePort }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  {{- end -}}
